name: Waka Readme

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
    description: Manually trigger readme update

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: False
          SHOW_LANGUAGE_PER_REPO: False
